### ISSUE TITLE
JWT grant process

### ISSUE THREAD

**Issue by aldoforce** [simkim/salesforcedx-gitlab-ci#1]
Hi!
I was wondering if you can add more details about the JWT token mechanism used for authentication.

on #sfdx-test.sh you use: 

`sfdx force:auth:jwt:grant --clientid $CI_SFDX_CONSUMER_KEY --jwtkeyfile "$CI_PROJECT_DIR/$CI_SFDX_KEY" --username $CI_SFDX_USERNAME --setdefaultdevhubusername -a HubOrg
`

I understand you created a Connected App with OAuth2 enabled for Digital Signatures to use JWT. Then declared an app key on $CI_PROJECT_DIR/$CI_SFDX_KEY

How you created that key? Did you used a certificate provided by a CA or self-signed? I see on some examples a reference to /app/server.key, can you explain more about that file?

--Aldo

**Comment by simkim** [comment]
Hi Aldo,

  First, Thank you very much for taking time considering my project.

  You can find documentation of the grant process at : 

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_jwt_flow.htm

  The certificate is self-signed, the documentation is at the next step : 

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_key_and_cert.htm

You can store it in your project to test, but it's more secure to use a gitlab variable (Settings > CI/CD Pipeline > Add a variable) for that.

in https://github.com/simkim/salesforcedx-gitlab-ci/blob/master/examples/gitlab-ci.yml I extract it from gitlab environment and base64 decode it (easier to pass encoded)

let's find a way to make it work for you and with this experience I could try to improve the documentation.

Best regards,

Gauthier
